### ISSUE TITLE
Upload on docker hub

### ISSUE THREAD

**Issue by orsinium** [eclecticiq/package.docker#3]
Is it uploaded on the docker hub? It could make usage a lot simpler.

**Comment by orsinium** [comment]
Well, it's already there. Then point on it?
https://hub.docker.com/r/eclecticiq/package

**Comment by ggeijteman-eiq** [comment]
[.travis.yml](https://github.com/eclecticiq/package.docker/blob/master/.travis.yml) used by [Travis CI](https://travis-ci.org/github/eclecticiq/package.docker) pushes these Docker images to Docker Hub. We should move this to Gitlab perhaps, but for now it works as designed :).

**Comment by orsinium** [comment]
Let's point on the DockerHub hosted image in the README. Perhaps, add a short example of docker-compose.yml as well.
